version: '3'

services:
  nats-server:
    image: nats:2.10.25-alpine

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/dark-mark-452418-d3/store-image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVER=nats://nats-server:4222

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/dark-mark-452418-d3/store-image-registry/products-ms
    environment:
      - PORT=3001
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_MS_DB=${ORDERS_MS_DB}
    image: southamerica-east1-docker.pkg.dev/dark-mark-452418-d3/store-image-registry/orders-ms
    environment:
      - PORT=3002
      - DATABASE_URL=${ORDERS_MS_DB}
      - NATS_SERVER=nats://nats-server:4222

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/dark-mark-452418-d3/store-image-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - NATS_SERVER=nats://nats-server:4222

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/dark-mark-452418-d3/store-image-registry/auth-ms
    environment:
      - PORT=3004
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}