apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/dark-mark-452418-d3/store-image-registry/payments-ms
          name: payments-ms
          env:
            - name: PORT
              value: "3001"
            - name: NATS_SERVER
              value: "nats://nats"
            - name: STRIPE_SUCCESS_URL
              value: "http://payments-ms:3003/payments/success"
            - name: STRIPE_CANCEL_URL
              value: "http://payments-ms:3003/payments/calceled"
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_secret
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_endpoint_secret
          resources: { }
status: { }
